# Generated by Django 4.0.1 on 2022-11-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poll',
            table='poll',
        ),
    ]
