# Generated by Django 4.0.1 on 2022-11-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_poll_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='user_id',
            new_name='user',
        ),
    ]
