# Generated by Django 4.0.1 on 2022-11-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_name',
            new_name='name',
        ),
    ]
